version: '2'

image: daocloud.io/imphoney/itxia

services:
  redis:
    image: redis
    command: redis-server --requirepass secret_password
    volumes:
      - ./redis:/var/lib/redis
    ports:
      - '6379:6379'
      
  db:
    image: mysql
    expose:
      - "3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/mysql.conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: cliff522..
      MYSQL_DATABASE: apidb

      
  website:
    build: .
    command: python manage.py runserver -h 0.0.0.0
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - .:/itxia
    ports:
      - '5000:5000'
    links:
      - db
      - redis

volumes:
  redis:
  db:
