version: '2'

services:
  redis:
    image: redis
    command: redis-server --requirepass secret_password
    volumes:
      - ./redis:/var/lib/redis
    environment:
      REDIS_PASSWORD: secret_password
    expose:
      - '6379'
      
  db:
    image: mysql
    expose:
      - "3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./config/mysql.cnf:/etc/mysql/mysql.conf.d/mysql.cnf
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: cliff522..
      MYSQL_DATABASE: apidb

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
      
  web:
    build: .
    command: bash -c "python manage.py db init && python manage.py db migrate -m 'v1_1' && python manage.py db upgrade && python manage.py testdb && gunicorn wsgi:application -b 0.0.0.0:80 || gunicorn wsgi:application -b 0.0.0.0:80"
    environment:
      PYTHONUNBUFFERED: 'true'
      REDIS_PASSWORD: secret_password
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: cliff522..
      MYSQL_DATABASE: apidb
    volumes:
      - ./src:/src
    expose:
      - "80"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

volumes:
  redis:
  db:
