version: '2.1'

services:
  redis:
    image: redis
    container_name: itxia_redis
    command: redis-server --requirepass secret_password
    volumes:
      - ./redis:/var/lib/redis
    env_file: .env
    expose:
      - '6379'
    healthcheck:
      test: "exit 0"
      
  db:
    image: mysql
    container_name: itxia_mysql
    expose:
      - "3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./config/mysql.cnf:/etc/mysql/mysql.conf.d/mysql.cnf
    env_file: .env
    healthcheck:
      test: "exit 0"

  nginx:
    image: nginx:latest
    container_name: itxia_nginx
    ports:
      - "5000:5000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
      
  web:
    build: .
    container_name: itxia_web
    command: bash -c "python manage.py db init && python manage.py db migrate -m 'v1_1' && python manage.py db upgrade && python manage.py testdb && gunicorn wsgi:application -b 0.0.0.0:5000 || gunicorn wsgi:application -b 0.0.0.0:5000"
    env_file: .env 
    volumes:
      - ./src:/src
    expose:
      - "5000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - db
      - redis